<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GcsDwg</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ACadSharp" Version="3.7.1" />
  </ItemGroup>
</Project>
